---
functional:
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность создать игру с другим пользователем
  - Пользователь должен иметь возможность создать игру с ботом
  - Пользователь должен иметь возможность подключиться к созданной игре как участник
  - Пользователь должен иметь возможность подключиться к созданной игре как зритель
  - Сайт должен предлагать шаблон загадок по уровню сложности и времени 
  - Сайт должен предлагать язык программирования, удобный пользователю
  - Пользователь должен видеть личную статистику по играм
  - У сайта должен быть общий рейтинг пользователей
  - У сайта должны быть ссылки на все сторонние ресурсы, где публикуются последние новости, и пользователи могли бы общаться
  - Во время игры пользователи должны иметь возможность проверить свой код с помощью авто-теста
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика .Например, 1000 одновременных пользователей.
implicit:
  - Пользователь должен иметь возможность посмотреть историю своих игр и их результат в виде решения
  - У сайта должна быть возможность менять язык интерфейса
  - Пользователь должен иметь возможность предложить собственную задачу и отправить ее на модерацию с последующим добавлением в шаблоны
  - При старте Игры сайт должен запрашивать демонстрацию экрана пользователя (во избежание жульничества)
  - У сайта должна быть возможность задонатить в знак поддержки работы сервиса 
  - У пользователя должна быть возможность пожаловаться на игрока, при подозрении в жульничестве
  - Пользователь должен иметь возможность отказаться от игры
